export const UI_LABELS = {
  observationCatalog: 'Beobachtungen-Katalog',
  observationCreate: 'Erstelle Beobachtung',
  angebotCatalog: 'Angebotskatalog',
  angebotCreate: 'Erstelle Angebot',
  angebotToday: 'Heutige Angebote',
  angebotAdd: 'Angebote hinzufügen',
  angebotManage: 'Angebote verwalten',
  weeklyTable: 'Tabelle',
  weeklyTableDaySelectionLabel: 'Tage berücksichtigen:',
  weeklyTableDaySelectionWorking: 'Arbeitstage ohne Einträge',
  weeklyTableDaySelectionHolidays: 'Feiertage',
  classSettings: 'Meine Klasse',
  freeDays: 'Freie Tage',
  timetable: 'Stundenplan',
};
