export const UI_LABELS = {
  observationCatalog: 'Beobachtungen-Katalog',
  observationCreate: 'Erstelle Beobachtung',
  angebotCatalog: 'Angebotskatalog',
  angebotCreate: 'Erstelle Angebot',
  angebotToday: 'Heutige Angebote',
  angebotAdd: 'Angebote hinzufügen',
  angebotManage: 'Angebote',
  themaDerWoche: 'Thema der Woche',
  weeklyTable: 'Tabelle',
  classSettings: 'Meine Klasse',
  freeDays: 'Freie Tage',
  timetable: 'Stundenplan',
  geldsammlungen: 'Geldsammlungen',
};
